/**
 * Layer C artwork — authored here, not generated by a library (§9.1).
 *
 * Each rosette is one hand-built petal rotated n times, so symmetry is structural
 * rather than the result of a spline fit. An earlier Catmull-Rom fit through
 * alternating radii produced asymmetric scribbles — see PROGRESS Scars.
 * Geometry: half-petal control arms are (4/3)·tan(Δ/4)·r, the exact circular-arc
 * construction, which is why the lobes read as engine-turning and not as blobs.
 */

export type Shape = { viewBox: string; paths: string[] };

export const SHAPES: Record<string, Shape> = {
  // 4 petals × 2 cubics, mirrored at 45° — the banknote rosette
  rosette: {
    viewBox: "-700 -700 1400 1400",
    paths: [
      "M 300.0 0.0 C 300.0 107.4 595.4 281.4 438.4 438.4 C 281.4 595.4 0.0 192.6 0.0 300.0 C -107.4 300.0 -281.4 595.4 -438.4 438.4 C -595.4 281.4 -192.6 0.0 -300.0 0.0 C -300.0 -107.4 -595.4 -281.4 -438.4 -438.4 C -281.4 -595.4 -0.0 -192.6 -0.0 -300.0 C 107.4 -300.0 281.4 -595.4 438.4 -438.4 C 595.4 -281.4 192.6 -0.0 300.0 0.0 Z",
      "M 212.1 212.1 C 136.2 288.1 222.0 620.0 0.0 620.0 C -222.0 620.0 -136.2 136.2 -212.1 212.1 C -288.1 136.2 -620.0 222.0 -620.0 0.0 C -620.0 -222.0 -136.2 -136.2 -212.1 -212.1 C -136.2 -288.1 -222.0 -620.0 -0.0 -620.0 C 222.0 -620.0 136.2 -136.2 212.1 -212.1 C 288.1 -136.2 620.0 -222.0 620.0 -0.0 Z",
    ],
  },
  // 3-petal outer + 6-petal counter-ring
  trefoil: {
    viewBox: "-700 -700 1400 1400",
    paths: [
      "M 329.4 84.1 C 288.9 243.0 470.1 532.8 172.9 616.2 C -124.3 699.6 -197.0 84.3 -237.6 243.2 C -278.2 402.1 -627.2 528.4 -489.6 326.6 C -352.0 124.8 -32.0 -562.0 -237.6 -243.2 C -443.2 75.6 -5.5 -493.7 -148.0 -468.6 C -290.5 -443.4 200.0 -133.4 200.0 -133.4 C 461.8 70.1 369.9 -74.9 329.4 84.1 Z",
      "M 250.0 0.0 C 250.0 59.2 462.7 138.5 407.0 235.0 C 351.3 331.5 125.0 157.3 125.0 216.5 C 73.7 246.1 -73.7 246.1 -125.0 216.5 C -176.3 186.9 -351.3 331.5 -407.0 235.0 C -462.7 138.5 -250.0 59.2 -250.0 0.0 C -250.0 -59.2 -462.7 -138.5 -407.0 -235.0 C -351.3 -331.5 -176.3 -186.9 -125.0 -216.5 C -73.7 -246.1 73.7 -246.1 125.0 -216.5 C 176.3 -186.9 351.3 -331.5 407.0 -235.0 C 462.7 -138.5 250.0 -59.2 250.0 0.0 Z",
    ],
  },
  // three concentric off-centre ovals — a certificate's embossed seal
  seal: {
    viewBox: "-700 -700 1400 1400",
    paths: [
      "M 600.0 0.0 C 600.0 232.0 331.4 420.0 0.0 420.0 C -331.4 420.0 -600.0 232.0 -600.0 0.0 C -600.0 -232.0 -331.4 -420.0 -0.0 -420.0 C 331.4 -420.0 600.0 -232.0 600.0 0.0 Z",
      "M 508.6 108.1 C 468.4 297.2 208.1 402.1 -72.8 342.4 C -353.7 282.6 -548.8 81.0 -508.6 -108.1 C -468.4 -297.2 -208.1 -402.1 72.8 -342.4 C 353.7 -282.6 548.8 -81.0 508.6 108.1 Z",
      "M 452.6 -80.8 C 477.2 74.6 302.6 231.5 62.6 269.5 C -177.4 307.5 -392.0 212.3 -416.6 56.9 C -441.2 -98.5 -266.6 -255.4 -26.6 -293.4 C 213.4 -331.4 428.0 -236.2 452.6 -80.8 Z",
    ],
  },
  // two counter-phase waves — banknote border lathe-work
  lathe: {
    viewBox: "-880 -260 1760 520",
    paths: [
      "M -840.0 110.0 C -739.2 110.0 -660.8 -110.0 -560.0 -110.0 C -459.2 -110.0 -380.8 110.0 -280.0 110.0 C -179.2 110.0 -100.8 -110.0 0.0 -110.0 C 100.8 -110.0 179.2 110.0 280.0 110.0 C 380.8 110.0 459.2 -110.0 560.0 -110.0 C 660.8 -110.0 739.2 110.0 840.0 110.0",
      "M -840.0 -110.0 C -739.2 -110.0 -660.8 110.0 -560.0 110.0 C -459.2 110.0 -380.8 -110.0 -280.0 -110.0 C -179.2 -110.0 -100.8 110.0 0.0 110.0 C 100.8 110.0 179.2 -110.0 280.0 -110.0 C 380.8 -110.0 459.2 110.0 560.0 110.0 C 660.8 110.0 739.2 -110.0 840.0 -110.0",
    ],
  },
};

/** Natural extent of each shape's own coordinate system (its viewBox width). */
export const NATURAL: Record<string, number> = {
  rosette: 1400, trefoil: 1400, seal: 1400, lathe: 1760, mark: 1400, fleuron: 1400,
};

/**
 * Placement of one shape. Positions are fractions of the viewport, so a shape
 * lands in the same *composition* at any window size; `span` is the shape's
 * target width as a fraction of viewport width.
 *
 * Earlier this used nested <svg x="%" y="%" width="%"> with preserveAspectRatio,
 * which put the lathe entirely below the fold and the mark off the right edge.
 * Explicit translate/rotate/scale in user units is predictable.
 */
export type Placement = {
  shape: keyof typeof SHAPES | "mark" | "fleuron";
  cx: number;   // 0..1 of viewport width
  cy: number;   // 0..1 of viewport height
  span: number; // target width as a fraction of viewport width
  rotate: number;
  drift: "a" | "b" | "c" | "d";
  reverse?: boolean;
};

/**
 * Per-route arrangements (§9.4). Same vocabulary, six compositions — the reader
 * should feel they are moving through a bound document, not reskinning one page.
 * Mobile takes the first two of each (§9.5).
 */
export const ARRANGEMENTS: Record<string, Placement[]> = {
  "/": [
    { shape: "rosette", cx: 0.10, cy: 0.30, span: 0.62, rotate: 0,   drift: "a" },
    { shape: "mark",    cx: 0.86, cy: 0.34, span: 0.40, rotate: -8,  drift: "c", reverse: true },
    { shape: "lathe",   cx: 0.54, cy: 0.86, span: 0.92, rotate: 0,   drift: "b" },
  ],
  "/model": [
    { shape: "seal",    cx: 0.16, cy: 0.40, span: 0.54, rotate: 6,   drift: "b" },
    { shape: "lathe",   cx: 0.88, cy: 0.44, span: 0.78, rotate: 90,  drift: "d", reverse: true },
    { shape: "trefoil", cx: 0.62, cy: 0.82, span: 0.40, rotate: 18,  drift: "a" },
  ],
  "/why": [
    { shape: "seal",    cx: 0.52, cy: 0.38, span: 0.66, rotate: -4,  drift: "c" },
    { shape: "rosette", cx: 0.90, cy: 0.78, span: 0.38, rotate: 22,  drift: "a", reverse: true },
    { shape: "lathe",   cx: 0.10, cy: 0.90, span: 0.70, rotate: 0,   drift: "b" },
  ],
  "/schemes": [
    { shape: "rosette", cx: 0.84, cy: 0.18, span: 0.50, rotate: 12,  drift: "d" },
    { shape: "seal",    cx: 0.08, cy: 0.72, span: 0.56, rotate: -8,  drift: "a", reverse: true },
    { shape: "trefoil", cx: 0.50, cy: 0.94, span: 0.36, rotate: 0,   drift: "c" },
  ],
  "/roadmap": [
    { shape: "lathe",   cx: 0.12, cy: 0.46, span: 0.80, rotate: 90,  drift: "b" },
    { shape: "mark",    cx: 0.74, cy: 0.74, span: 0.44, rotate: 6,   drift: "d", reverse: true },
    { shape: "rosette", cx: 0.94, cy: 0.14, span: 0.34, rotate: -14, drift: "a" },
  ],
  "/join": [
    { shape: "seal",    cx: 0.50, cy: 0.44, span: 0.58, rotate: 0,   drift: "c" },
    { shape: "fleuron", cx: 0.84, cy: 0.82, span: 0.30, rotate: -10, drift: "a", reverse: true },
  ],
};

export const arrangementFor = (path: string): Placement[] =>
  ARRANGEMENTS[path] ?? ARRANGEMENTS["/"];
